INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('巴林左旗清源污水处理厂', '污水厂', '119.41', '43.96', '巴林左旗林东镇八一村南沙里河北岸', '范宗辉', '水污染治理', '范宗辉', '13947659435', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '365', 'http://nmgepb.gov.cn:8088/enterprisemonitor/appportal.jsp?sysid=jcxx', '巴林左旗清源污水处理厂位于林东镇八一村南沙里河北岸，占地60亩，经自治区发改委以内发改投字[2004]1175号文件批复建设。工程于2005年10月开工建设，到2007年10月全部完工，2007年11月投入运行。日处理规模2万吨/日。', '76108925-7', '15000000', 'wscfzh@sina.com', '10232', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('巴彦淖尔市临河东城区污水处理有限公司', '污水厂', '', '', '巴彦淖尔市临河东城区', '张国臣', '水污染治理', '张勇', '0478-8950903', NULL, NULL, '巴彦淖尔市水土环境监测中心', '巴彦淖尔市水土环境监测中心', NULL, NULL, NULL, NULL, '全年', 'http://nmgepb.gov.cn:8088/enterprisemonitor/enterprise-info!getCompanyInfo.action?companyid=10549', '巴彦淖尔市临河东城区污水处理工程是由巴彦淖尔经济技术开发区管委会投资建设，项目位于开发区五原街南，建材路西侧，占地面积300亩, 一期工程总投资2.08亿元，建设规模为日处理污水4万吨。工程主要由12座污水处理池及相配套的14座附属建筑物组成，二期工程总投资1.73亿元,建设规模为日处理污水6万吨。针对处理开发区企业的工业污水及部分生活污水，工艺采用预处理＋水解酸化＋A/O＋二沉池＋臭氧氧化＋曝气生物滤池＋提升池＋三相催化氧化反应器＋稳定池＋高密度沉淀池的组合处理工艺，处理后水质达到《城镇污水处理厂污染物排放标准》（GB18918-2002）一级B标准排放至排干渠。', '05058330-4', '15000000', '', '10549', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('巴彦淖尔市污水处理厂', '污水厂', '107.46', '40.78', '内蒙古巴彦淖尔市经济技术开发区', '苏和', '其他水利管理', '杨东其', '18604781958', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 'http://nmgepb.gov.cn:8088/enterprisemonitor/appportal.jsp?sysid=jcxx', '巴彦淖尔市污水处理厂位于巴彦淖尔市经济技术开发区，一期工程建设污水处理规模10万m3/d,中水回用6万m3/d。一期污水处理共2套系统，单套处理规模5万m3/d，主要处理城区生活污水及部分工业废水。污水处理采用“预处理+A2/O+二沉池+活性砂滤池+紫外消毒”的组合处理工艺，处理后污水厂出水水质达到《城镇污水处理厂污染物排放标准》（GB18918-2002）一级A标准。', '67694591X', '15000000', 'yangdongqi302005@163.com', '10314', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('巴彦淖尔市飞尚铜业有限公司', '废气 重金属', '106.85', '40.97', '乌拉特后旗青山工业园区', '黄文来', '铜冶炼', '乌日娜', '18704992911', NULL, NULL, '乌拉特后旗环境监测站', '乌拉特后旗环境监测站', NULL, NULL, NULL, NULL, '270', 'http://nmgepb.gov.cn:8088/enterprisemonitor/enterprise-info!getCompanyInfo.action?companyid=10103', '公司位于内蒙古自治区巴彦淖尔市乌拉特后旗青山工业园区内，年产粗铜（阳极板）10万吨、工业硫酸37.5万吨，是一个铜冶炼现代化的企业。“飞尚法”冶炼技术和工艺是国内外最先进的铜冶炼生产工艺之一，拥有自主知识产权', '77224743-3', '15000000', '549815299@qq.com', '10103', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('巴彦淖尔市鸿德再生资源开发有限公司', '污水厂', '108‘’11’', '40‘’28‘', '乌拉特前旗乌拉山镇', '哈斯', '', '赵慧', '13847877861', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '365', 'http://nmgepb.gov.cn.:8088/enterprisemonitor/enterprise-info!getCompanyInfo.action?companyid=10219', '巴彦淖尔市鸿德再生资源开发有限公司乌拉特前旗污水处理厂是对乌拉山镇生活废水进行净化处理的环保企业。企业由巴彦淖尔市发改委批准立项，设计规模日处理污水能力8万吨。一期工程日处理污水2万吨，总投资8550万元人民币，占地面积193亩。主要设备由德国进口，采用德国冯·诺顿西百沃克浮链式多级A/O污水处理工艺，运用低负荷活性污泥法，对生活废水进行生物化学处理，达到《城市污水处理厂污染物排放标准》一级A标准。达标水可用于工业、消防和园林绿化。生产中的污泥经过科学处理后，可用作农林和园艺施肥。', '797175931', '15000000', 'by-hongde@163.com', '10219', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('巴彦淖尔中联水泥有限公司', '废气', '109.14.48', '40.59.59', '巴彦淖尔市乌拉特前旗大佘太镇白彦花村', '孙荣泽', '制造业', '张桂军', '15134977703', NULL, NULL, '乌拉特前旗环境保护监测站', '乌拉特前旗环境保护监测站', NULL, NULL, NULL, NULL, '4月-10月', 'http://nmgepb.gov.cn:8088/enterprisemonitor/enterprise-info!getCompanyInfo.action?companyid=10565', '巴彦淖尔中联水泥有限公司为中国联合水泥集团旗下重点骨干企业，企业已通过了GB/T19000质量体系、GB/T24001环境管理体系、GB/T28001职业健康安全3项体系认证以及国家级安全标准化一级企业验收。', '72014152-2', '15000000', '15134977703@163.com', '10565', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('巴彦淖尔紫金有色金属有限公司', '废气 重金属', '107.07', '41.11', '巴彦淖尔市乌拉特后旗东升庙工业园区', '廖元杭', '铅锌冶炼', '毕小强', '4666998', NULL, NULL, '乌拉特后旗环境监测站', '乌拉特后旗环境监测站', NULL, NULL, NULL, NULL, '全年', 'http://nmgepb.gov.cn:8088/enterprisemonitor/enterprise-info!getCompanyInfo.action?companyid=10212', '我公司与2004年11月立项建设10万吨锌冶炼，采用离子液脱硫的方式去除制酸尾气中的二氧化硫。在2007年扩建二期10万吨锌冶炼，采用活性焦脱硫的方式去除制酸尾气中的二氧化硫。', '767866448', '15000000', '912160900@qq.com', '10212', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('白音华金山发电有限公司', '废气', '118.27', '44.48', '内蒙古自治区锡林郭勒盟西乌珠穆沁旗白音华工业园区', '金玉军', '火力发电', '包英杰', '15904790074', NULL, NULL, '内蒙古自治区环境监测中心站', '内蒙古自治区环境监测中心站', NULL, NULL, NULL, NULL, '365', 'http://nmgepb.gov.cn:8088/', '白音华金山发电有限公司位于内蒙古锡林郭勒盟西乌珠穆沁旗境内，属坑口电厂，规划总装机容量为4×600MW。一期工程建设2×600MW空冷燃煤发电机组，配置2台2080吨/小时亚临界自然循环锅炉。1、2号机组分别于2010年8月8日和9月1日完成168小时试运行。', '783036623', '15000000', 'byhjsbyj.ok@163.com', '10173', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('赤峰富龙热电厂有限责任公司', '废气', '118.5457', '42.1658', '赤峰富龙热电厂', '李春晓', '电力、热力的生产和供应业', '王学军', '0476-8410313', NULL, NULL, '赤峰绿康环境检测有限公司 ● 机构名称', '赤峰绿康环境检测有限公司 ● 机构名称', NULL, NULL, NULL, NULL, '200天', 'http://nmgepb.gov.cn:8088/enterprisemonitor/enterprise-info!getCompanyInfo.action?companyid=10250', '赤峰富龙热电厂有限责任公司位于赤峰市松山区西站大街，属于热、电生产供应业。建设规模为2台29MW循环流化床锅炉、4台75t/h循环流化床蒸汽锅炉，以及3台12MW抽汽凝汽式汽轮机发电机组。总装机容量36MW。年供热能力270万GJ，年供电能力为1.8亿KWh。', '58519172-9', '15000000', 'wangxuejun861@163.com', '10250', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('赤峰热电厂', '废气', '118.92', '42.27', '内蒙古自治区赤峰市长青街东段', '高德民', '电力、热力的生产和供应业', '李全', '0476-8262182', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '365', 'http://nmgepb.gov.cn:8088/enterprisemonitor/enterprise-info!getCompanyInfo.action?companyid=10252', '赤峰热电厂始建于1958年，位于内蒙古自治区赤峰市红山区,距市区中心约2公里，目前总装机容量346MW。其中A厂（老厂）发电装机容量为76MW,B厂（新厂）为四期扩建工程，共建两台供热机组，发电装机总容量为270MW,赤峰热电厂现隶属于中国电力投资集团蒙东能源集团公司,是一个中型热电联产企业，除发电外，还承担着向赤峰市区19家工业企业提供生产用汽和中心城区居民1200多万平方米生产生活建筑冬季采暖用热任务，是赤峰市的骨干热源单位。', '114791584', '15000000', '13514860158@163.com', '10252', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('包头东宝生物技术股份有限公司', '废水', '109度51分15秒', '40度38分13秒', '包头稀土高新区黄河大街46号', '王军', '生物、生化制品的制造', '杨生茂', '0472-5319900', NULL, NULL, '包头市天禾环境技术有限责任公司', '包头市天禾环境技术有限责任公司', NULL, NULL, NULL, NULL, '330', 'http://www.dongbaoshengwu.com', '包头东宝生物技术股份有限公司成立于1997年，是一家专业的生物制品国家级高新技术企业。主营“金鹿”牌明胶、“圆素”牌胶原蛋白及“白云”牌磷酸氢钙产品。公司注册资本19754.8万元，拥有总资产约5亿元。', '603267185', '15000000', '13015252606@126.com', '10376', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('包头鹿城水务有限公司', '污水厂', '109.85', '40.59', '包头市九原区麻池镇', '李然然', '污水处理及其再生利用', '马长宝', '04725980118', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '连续生产', 'http://nmgepb.gov.cn:8088/enterprisemonitor/webpage!indexPage.action', '包头市南郊污水处理工程及中水回用项目是由北京桑德环保集团以BOT形式建设运营的污水处理厂项目，占地面积328亩，处理规模污水20万吨/日，中水5.5万吨/日。污水处理采用A2/O+SNP工艺进行生化处理，能够降解CODcr并同时具有脱氮除磷功能。运行出水水质达到国家《城镇污水处理厂污染物排放标准》（GB18918-2002）一级A标准。中水处理采用高密度沉淀池+V型滤池（混凝、沉淀、过滤）处理工艺，出水达到市政用水和冷却用水标准。', '764467604', '15000000', '278342444@qq.com', '10202', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('包头东华热电有限公司', '废气', '110.07', '40.58', '包头市东河区国家生态工业（铝业）示范园区', '王如祥', '电力、燃气及水的生产和供应业', '付佐斌', '0472-4343529', NULL, NULL, '北京航天益来有限公司', '北京航天益来有限公司', NULL, NULL, NULL, NULL, '2903', 'http://nmgepb.gov.cn:8088/enterprisemonitor/webpage!indexPage.action', '包头东华热电有限公司于2003年4月2日注册成立的热电联产企业，2012年底在册职工299人。2005年12月投产发电，是我国高寒地区首家使用湿法脱硫的电厂、内蒙古地区首家使用中水的电厂和首家单机容量300MW热电厂。', '74793991-3', '15000000', '47087240@qq.com', '10009', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('包头钢铁（集团）有限责任公司', '废气', '106.9039', '39.6147', '包头钢铁（集团）有限责任公司厂区白灰厂', '范新平', '非金属矿采选业', '范广宇', '13847323003', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '288', 'http://nmgepb.gov.cn:8088/enterprisemonitor/enterprise-info!getCompanyInfo.action?companyid=10253', '包钢乌海矿业公司位于乌海市海勃湾区卡布其境内，始建于1959年，属非煤露天矿山，设计年生产石灰石200万吨，白灰40万吨，建有两条生产白灰的回转窑。', '81467070-8', '15000000', '382233497@qq.com', '10253', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('包头华鼎铜业发展有限公司', '废气', '109', '40', '包头稀土高新区希望工业园区', '王贺平', '有色金属冶炼及压延加工业', '张丽', '0472-2293878', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 'http://www.bthdty.com/', '包头华鼎铜业发展有限公司，于2003年9月在包头国家稀土高新区注册成立。公司注册资本金5295.652万美元，包头华鼎铜业发展有限公司由香港兴益金属材料有限公司、中国金川投资控股有限公司、昆山远大矿产物资有限公司、内蒙古高新控股有限公司四家股东共同出资组成。 
     作为新型的民营企业，公司以严格的管理制度与科学的绩效管理相结合，把理解人、尊重人、关心人、塑造人的人本观念变成企业的灵魂。公司已形成了适合新型民营企业发展的科学的招聘、培训、绩效考核、薪酬激励等人力资源管理体系，建立了规范的管理制度，管理流程，劳动保障体系，做到待遇留人、情感留人、机制留人，为每一位员工搭建一个展示自己聪明才智的平台。', '75258087X', '15000000', '47792808@qq.com', '10276', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('包头冀东水泥有限公司', '废气', '110.0618', '41.5230', '窑尾预热器', '朱长君', '水泥制造', '张星', '13847394045', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', '包头冀东水泥有限公司由唐山冀东水泥股份有限公司独家投资建设。公司于2009年9月正式注册成立，厂址位于内蒙古达茂旗西北40公里处，项目占地面积465亩。一期项目投资9亿元，建设一条日产4500吨熟料水泥生产线（带纯低温余热发电），项目已于2011年10月28日正式进入试生产期,设计年产熟料160万吨，水泥80万吨。产品种类分别是P.O42.5,P.C32.5，缓凝32.5.', '692885099', '15000000', '597042029@qq.com', '10583', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('包头铝业有限公司', '废气', '109度27分40秒', '40度27分58秒', '包头市东河区毛其来', '柴永成', '有色金属冶炼及压延加工业', '银光', '0472-6935168', NULL, NULL, '内蒙古华质检测技术有限公司', '内蒙古华质检测技术有限公司', NULL, NULL, NULL, NULL, '365', 'http://nmgepb.gov.cn:8088/enterprisemonitor/appportal.jsp?sysid=jcxx', '包头铝业位于包头国家生态（铝业）示范园区内，始建于1958年。2003年6月，纳入中国铝业公司。现有三个铝电解生产系列，一个碳素系列，2*330MW热电联产机组。生产能力分别为年产原铝55万吨，炭素制品12万吨。', '676383845', '15000000', '30986540@qq.com', '10148', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('包头市白云鄂博矿区博源给排水有限责任公司', '污水厂', '109度58分41秒', '41度46分38秒', '包头市白云鄂博矿区矿山路以东铁矿电子楼斜对面', '武永历', '环境管理业', '刘建国', '18648279875', NULL, NULL, '内蒙古加通环境检测治理有限公司', '内蒙古加通环境检测治理有限公司', NULL, NULL, NULL, NULL, '', 'http://nmgepb.gov.cn:8088/enterprisemonitor/appportal.jsp?sysid=jcxx', '包头市白云鄂博矿区污水处理厂位于包头市白云鄂博城区东北部（地质道东侧），建设规模为1万 吨/日，管网内提升污水泵站2座，重力流排管道和泵站压力管道7.6公里。主要工艺：水解酸化+生物接触氧化法工艺，出水水质为一级B标准，采取直接脱水污泥处理工艺。', '680017665', '15000000', '1549978267@qq.com', '10289', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('包头市东河区东水质净化厂', '污水厂', '110度14分6秒', '40度71分57秒', '包头市南海公园东200米', '郝振华', '水污染治理', '董军伟', '13948923344', NULL, NULL, '包头金惠达自动化控制有限公司 ● 机构名称', '包头金惠达自动化控制有限公司 ● 机构名称', NULL, NULL, NULL, NULL, '连续', 'http://nmgepb.gov.cn:8088/enterprisemonitor/appportal.jsp?sysid=jcxx', '随着国家对节能减排工作要求的不断提高，对黄河中上游流域的水污染防治提出了更严格的要求，目前东河东水质净化厂的处理能力、处理标准已不能满足社会发展的需要，在市委、市政府的大力支持下和市建委的领导下，包头市排水产业有限责任公司实施了东河东水质净化厂扩建工程，该工程包括东河东水质净化厂、东河东水质净化厂污水回用、相应配套管网工程。工程总投资2.194亿元RMB。新建污水处理厂占地89500m2，目前规模扩建至5.5万m3/日，远期规模10万m3/日。处理采用了改良A2/O同步除磷脱氮工艺，出水水质达到国家一级A排放标准，该项目于2013年8月投入试运行。
东河东水质净化厂隶属于包头市排水产业有限责任公司，于2000年12月开始建设，2004年8月建成投产；工程总投资4882万元（不包括外网），其中日元贷款折人民币2809万元；东厂地处东河区东河槽下游河漫滩，全厂占地面积2.8公顷，服务面积7.08km2,服务人口8.29万人，服务区域包括东河区环城东路，南二里半、东河西路，西二里半、站南路、民航小区，处理的污水主要以生活污水为主，设计日处理污水量2万吨。', '74010811301', '15000000', '937325516@qq.com', '10115', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "plant_app_tcx"."tb_enterprise" ("qy_name", "qy_wrylx", "qy_jd", "qy_wd", "qy_address", "qy_corporation", "qy_industry", "qy_link_user", "qy_link_phone", "qy_tysj", "qy_auto_monitor_style", "qy_manual_monitor_style", "qy_auto_monitor_operation_style", "qy_pfwrwmc", "qy_zyscgy", "qy_zycp", "qy_zlss", "qy_lead_time", "qy_url", "qy_introduce", "qy_organization_code", "province_id", "qy_link_email", "qy_id", "qy_style", "qy_unit_category", "qy_register_type", "qy_manager_dept", "qy_scale", "qy_fax", "qy_city", "qy_city_id") VALUES ('徐矿集团新疆阿克苏热电有限公司', '废气企业', '41.08099', '41.08099', '阿克苏市西工业园区', '方民主', '火力发电', '高永', NULL, NULL, '自动监测', '委托监测机构：', '委托第三方运营机构：', NULL, NULL, '电', NULL, '连续', NULL, '1.1 企业概况	
徐矿集团新疆阿克苏热电有限公司位于阿克苏市西工业园区，是一座以发电和供热为主的热电厂。电厂于2010年3月份开工建设，2011年底完成机组双投，一期工程发电总装机400MW，供热能力270MW，承担着阿克苏地区电网60%的电负荷和阿克苏市区的供热任务。
经过近四年的火力发电生产管理和实践，电厂建立起了完整的电力生产管理制度和运行、检修职工队伍，熟练掌握了电力生产的管理与技术。特别是近三年来，电厂在安全生产和发电运行方面积累了丰富的经验，保持了同型机组在安全和指标管理趋于同类机组先进水平。依靠科技进步，促进企业环保与安全和谐发展。2013年六月完成了中水管道及提升泵房施工，为使用阿克苏市污水厂中水，减少西湖地表水创造了条件，2014年三月完成两台机组脱硝工程并投入运行，减少氮氧化物排放，减少环境空气污染，有效提高阿克苏市及周边居民生活环境质量；全厂计算机网络建设、两融合建设，220KV系统保护改造升级、电压自动控制系统（AVC）、自动发电控制（AGC）系统、电力系统稳控系统建设、全厂视频监控系统安装、厂级自动办公系统（MIS）和监控（SIS）系统建设等，提高了电厂的现代化水平。
1.2 生产概况
徐矿阿克苏热电有限公司目前装有2台670吨/小时超高压一次中间再热煤粉炉，配套2台200MW超高压抽汽凝汽式汽轮发电机组，发电机采用水氢氢冷气方式；采用双室四电场静电除尘器，烟气使用石灰石-石膏湿法烟气脱硫技术，应用低氮燃烧+SCR脱硝系统控制氮氧化物产生；机组采用闭式循环冷却方式。
目前，徐矿集团新疆阿克苏热电有限公司年发电机组利用小时数在5000小时，发电量约为20亿千瓦.时，耗煤约80万吨。
1.3 生产工艺
燃煤送至磨煤机内磨成煤粉，磨碎的煤粉由热空气携带送入锅炉的炉膛内燃烧；煤粉燃烧后形成的热烟气沿锅炉的水平烟道和尾部烟道流动，放出热量，最后进入静电除尘器，将灰分离出来；洁净的烟气在引风机和增压风机的作用下送至脱硫装置除去二氧化硫后，通过烟囱排入大气。燃煤燃尽的灰渣落入炉膛下面的渣斗内，经风冷式排渣机、碎渣机和斗式提升机送至渣库，再由干式卸料机或湿式卸料机卸至卡车送综合利用；锅炉产生的高压蒸汽经由管道送至汽轮机，汽轮机将热能转换为机械能带动发电机，发电机将机械能转换为电能，经由主变压器升压送至电网；做功后的蒸汽进入凝汽器，汽轮机抽汽供给热网加热器，该加热器将热网循环水加热供给热用户；生产过程中产生的废水分别采取相应的措施处理后回用。
1.4 污染源产生及处置
1.4.1锅炉废气
废气主要是燃煤过程中产生的烟气，其主要污染物有SO2、烟尘、NOX等。对烟尘控制采用二室四电场静电除尘器，石灰石-石膏湿法脱硫对烟尘也有一定的去除作用；对SO2的控制采用石灰石-石膏湿法脱硫；对NOX的控制主要是采用低氮燃烧技术控制NOx的排放浓度。烟气经处理后通过180米烟囱排放。
1.4.2 废水污染物
废水包括生活废水和生产废水，其中生产废水包括工业废水、脱硫废水、含煤废水等。主要生产废水和生活污水处理及排放情况如下：
（1）生活污水
生活污水主要产生于浴室、食堂、办公楼及车间等。该工程建设一座生活污水处理站，设有1套地埋式生活污水处理装置，处理设施处理能力为5m3/h，该处理设施采取间断运行方式，当水量达到液位后自动运行。生活污水经二级生化处理后回用于厂区绿化。
（2）工业废水
工业废水主要为化学水处理车间排水、含油废水、锅炉酸洗水、冷却水等。该工程设置工业废水处理站一座，处理能力为20m3/h。设施采取间断运行方式，当水量达到一定量时设备自动运行。废水经处理后进入复用水池回用于冷却塔补充水。
（3）含煤废水
含煤废水主要为处理输煤系统冲洗排水、输煤栈桥煤仓间冲洗水及煤场雨水等，主要污染物为SS。该工程新建1座含煤废水处理站，处理站安装1套含煤废水净化装置，处理能力为10m3/h，设备随沉淀池水位高低启停，当水位达到设计水位时启动。该部分废水为间断产生，废水经处理后用于输煤栈桥冲洗和煤场喷淋。
( 4 )脱硫废水
工程设置1套脱硫废水处理系统，处理能力为20m3/h，用以处理装置排出的脱硫废水，该部分废水为连续产生，废水经处理后回用于干灰加湿、灰场降尘等。
目前，全厂无外排工业废水。
1.4.3 固体废物
固体废物主要为煤粉在炉膛内燃烧后生成炉渣和灰以及脱硫石膏。该工程采用灰渣分除、干除灰系统，排放的灰渣由输送系统分别送至灰库、渣库。全年灰产生量约11.72万t/a，渣产生量约1.13万t/a，石膏产生量约为2.5万t/a。灰渣全部综合利用，综合利用不畅时，送至事故灰场贮存。电厂已阿克苏鑫联环保工程公司、阿克苏康辉工贸有限公司、库车县鑫泰商贸有限公司灰渣、石膏买卖合同。目前电厂灰渣与石膏利用率为100%。
1.4.4 厂界噪声
电厂厂界外昼间、夜间噪声监测结果全部达到《工业企业厂界环境噪声排放标准》（GB12348－2008）中III类标准要求。
1.5 厂区周围环境情况
厂区位于阿克苏市西部的西工业园内，地理坐标为：东经86°9.8′，北纬41°4.7′，该区域地形相对平坦，西高东低，东西两端约有60m的高差；厂区东侧为西湖路、北侧为克拉玛依路、南侧为沈阳路、西侧为大庆路。厂区东西最大宽度350米，南北最大长度570米，占地面积20hm厂区距阿克苏市中心直线距离11km.
本企业自行监测方式为自动监测与手工监测相结合方式，自动监测为企业自运维或委托第三方运营机构进行运维，承担委托运维的单位名称为山西鑫华翔科技发展有限公司；手工监测为企业自承担监测或委托阿克苏地区社会化监测机构开展监测，承担委托监测的单位名称为阿克苏地区环保局。', '689564657', '65000000', NULL, '10213', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);







INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 23:00:00', '氮氧化物', '108.76', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 23:00:00', '二氧化硫', '116.34', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 23:00:00', '颗粒物', '17.65', '30', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 22:00:00', '氮氧化物', '112.85', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 22:00:00', '二氧化硫', '71.19', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 22:00:00', '颗粒物', '14.61', '30', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 21:00:00', '氮氧化物', '115.6', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 21:00:00', '二氧化硫', '105.2', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 21:00:00', '颗粒物', '14.74', '30', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 20:00:00', '氮氧化物', '122.96', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 20:00:00', '二氧化硫', '100.64', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 20:00:00', '颗粒物', '15.37', '30', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 19:00:00', '氮氧化物', '129.15', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 19:00:00', '二氧化硫', '115.43', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 19:00:00', '颗粒物', '14.67', '30', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 18:00:00', '氮氧化物', '141.47', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 18:00:00', '二氧化硫', '101.14', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 18:00:00', '颗粒物', '15.83', '30', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 17:00:00', '氮氧化物', '130.75', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 17:00:00', '二氧化硫', '101.34', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 17:00:00', '颗粒物', '16.02', '30', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 16:00:00', '氮氧化物', '121.79', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 16:00:00', '二氧化硫', '75.71', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 16:00:00', '颗粒物', '16.81', '30', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '锅炉尾部和水平烟道', '2016-05-22 15:00:00', '氮氧化物', '120.47', '200', NULL, '10424');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 23:00:00', '氮氧化物', '179.8388', '300', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 23:00:00', '二氧化硫', '186.897', '200', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 23:00:00', '颗粒物', '28.8185', '50', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 22:00:00', '氮氧化物', '179.1616', '300', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 22:00:00', '二氧化硫', '161.8824', '200', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 22:00:00', '颗粒物', '22.4208', '50', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 21:00:00', '氮氧化物', '172.5482', '300', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 21:00:00', '二氧化硫', '129.5971', '200', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 21:00:00', '颗粒物', '18.0049', '50', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 20:00:00', '氮氧化物', '175.7213', '300', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 20:00:00', '二氧化硫', '94.8581', '200', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 20:00:00', '颗粒物', '15.7961', '50', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 19:00:00', '氮氧化物', '191.3847', '300', NULL, '10057');
INSERT INTO "plant_app_tcx"."tb_acquisition" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '脱硫塔', '2016-05-20 19:00:00', '二氧化硫', '127.5125', '200', NULL, '10057');






INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('35000000', '2#炉设施出口', '2017-10-11 19:00:00', '一氧化碳折算', '0', '100', '是否停产： 否', 'YQKCMWRD-B2CL-YBCO-DS4J-Q53ETVSWS1LR');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('44000000', '4号机组', '2017-10-12 07:00:00', '二氧化硫', '30.1175', '100', '是否停产： 正常', 'ad89a7aa-4074-11e3-a6a2-6c626d51ef74');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('36000000', '二期6号机组', '2017-08-23 21:00:00', '烟尘折算', '14.22', NULL, NULL, '609810008');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('35000000', '2#炉排放口', '2017-10-12 07:00:00', 'SO2折算浓度', '50.201', '100', '是否停产： 否', 'VGS3I9K7-6R98-SP4V-ONBG-1VQ689VWI8S8');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('41000000', '2#脱硫塔', '2017-10-12 04:00:00', '氮氧化物', '22.57', '650', NULL, '41018379064593-7(0)');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('61000000', '7号脱硝出口', '2017-10-12 08:00:00', '氮氧化物', '22.284', NULL, NULL, '610500000018');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '烟囱', '2017-07-31 23:00:00', '二氧化硫', '97.7179', '200', NULL, '10353');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('35000000', '1#焚烧炉出口', '2017-10-12 07:00:00', '二氧化硫', '15.721', '100', '是否停产： 否', 'P9VLT7AK-ANXT-U735-TZX9-5KKPILTO7DDP');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('44000000', '4号机组', '2017-10-12 07:00:00', '烟尘', '1.3292', '30', '是否停产： 正常', 'ad89a7aa-4074-11e3-a6a2-6c626d51ef74');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('61000000', '沮河电厂烟囱总排口', '2017-10-12 09:00:00', '烟尘', '4.416', NULL, NULL, '610632000001');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('61000000', '3号出口', '2017-01-26 00:00:00', '氮氧化物', '0', NULL, NULL, '610000000001');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '排气口监测点', '2017-04-13 23:00:00', '氮氧化物', '65', '200', NULL, '10074');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('61000000', '沮河电厂2炉脱硫出口', '2017-10-12 08:00:00', '二氧化硫', '0', NULL, NULL, '610632000001');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '雁南热电厂3号锅炉', '2016-12-15 17:00:00', '氮氧化物', '206.0405', '0', NULL, '10339');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '8号机废气总排口', '2017-07-31 23:00:00', '二氧化硫', '27.37', '200', NULL, '10393');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('52000000', '四号机组脱硫净烟气', '2017-05-15 13:00:00', '烟尘', '10.53', '30', NULL, '520400000007');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('35000000', '1#炉设施出口', '2017-10-12 07:00:00', '烟尘', '5.133', '30', '是否停产： 否', 'YQKCMWRD-B2CL-YBCO-DS4J-Q53ETVSWS1LR');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '排气口监测点', '2017-04-13 23:00:00', '二氧化硫', '137', '200', NULL, '10074');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('42000000', '湖北华电襄阳发电有限公司(2＃脱硫环保口)', '2017-07-06 00:00:00', '二氧化硫', '118.91', '200', '', '3034');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('41000000', '1#燃煤锅炉', '2017-10-11 06:00:00', '氮氧化物', '113.05', '200', NULL, '41180073551491-8');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('61000000', '1号出口', '2015-03-26 15:00:00', '氮氧化物实测', '84.66', '100', '达标', '610000000009');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('41000000', '2号电站锅炉脱硫岛', '2017-09-16 19:00:00', '烟尘', '0.31', '50', NULL, '41060377940430-7');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('41000000', '5号后', '2017-10-12 04:00:00', '氮氧化物', '28.41', '200', NULL, '41010261471114-9');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('35000000', '2号焚烧炉烟囱', '2017-10-11 18:00:00', '一氧化碳', '0', '100', '是否停产： 否', '3DHCG6NL-Z7Z7-WK8J-LH8A-WU1JPXTZU9PD');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('61000000', '沮河电厂1炉A脱硝出口', '2017-10-12 09:00:00', '氮氧化物', '44.591', NULL, NULL, '610632000001');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('35000000', '2#炉排放口', '2017-10-12 07:00:00', '氮氧化物', '129.681', '300', '是否停产： 否', 'VGS3I9K7-6R98-SP4V-ONBG-1VQ689VWI8S8');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('41000000', '6号炉除尘后', '2017-09-30 23:00:00', '氮氧化物', '147.25', '400', NULL, '41100117427292-x');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('35000000', '2#炉排放口', '2017-10-12 07:00:00', '烟尘折算浓度', '8.171', '30', '是否停产： 否', 'VGS3I9K7-6R98-SP4V-ONBG-1VQ689VWI8S8');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('61000000', '3号出口', '2017-07-10 01:00:00', '二氧化硫', '0', '200', '达标', '610632000001');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('61000000', '1号出口', '2015-03-26 15:00:00', '二氧化硫实测', '158.17', '50', '超标', '610000000009');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('33000000', '1号炉混合烟道', '2017-10-12 08:00:00', '氮氧化物(mg/m3)', '27.43', '100', '正常', '33000000-2161');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '自动监测废气点1#', '2017-06-19 23:00:00', '氮氧化物', '27.724583', '50', NULL, '10213');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('35000000', '3#锅炉排放口', '2017-05-20 07:00:00', 'NOx折算浓度', '0', '100', '是否停产： 是', '8P0VGMBX-GAR3-X6YY-JK5D-N0TQ29ISE8RD');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('41000000', '6号炉除尘后', '2017-09-30 23:00:00', '二氧化硫', '35.57', '260', NULL, '41100117427292-x');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('35000000', '3#锅炉排放口', '2017-05-20 07:00:00', '氮氧化物', '0', '100', '是否停产： 是', '8P0VGMBX-GAR3-X6YY-JK5D-N0TQ29ISE8RD');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('15000000', '自动监测废气点1#', '2017-06-19 23:00:00', '二氧化硫', '2.312916', '35', NULL, '10213');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('61000000', '沮河电厂2炉脱硫出口', '2017-10-11 02:00:00', '氮氧化物', '0', NULL, NULL, '610632000001');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('35000000', '2#锅炉烟道出口', '2017-10-12 07:00:00', '烟尘', '2.34', '80', '是否停产： 否', 'RT29CXKS-EQ20-OOON-6ZRB-2VWK5624BMWU');
INSERT INTO "plant_app_tcx"."tb_acquisition_new_data" ("province_id", "monitor_point", "monitor_time", "project_id", "monitor_value", "standard_limit_value", "evaluation_criterion", "enterprise_id") VALUES ('61000000', '2号机组烟气排放口', '2017-10-12 08:00:00', '氮氧化物', '25.462', '100', '达标', '610000000001');
